import type { Metadata } from "next";
import { Google_Sans } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const googleSans = Google_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "The Enabler",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <NavBar/>
      <html
        lang="en"
        className={`${googleSans.className} h-full antialiased`}
      >
        <body className="min-h-full flex flex-col">{children}</body>
      </html>
      <Footer/>
    </>
  );
}
